package com.bol.spinner.editor.spinner;

import cn.hutool.core.text.CharSequenceUtil;

import java.util.List;

public enum SpinnerSettingNameConfig {
    FORM_FIELD("Access Expression,Access Function,Access Mask,Access Program,Add Icon,Add Link,Add Text,Add Tooltip,Additional Query,Admin Type,Allow Guide Edit,Alternate OID expression,Alternate Type expression,Calendar Function,Calendar Program,Category,Cols,Column Count,Column Style,Command,Counter Link,Counter Style,Counter Tooltip,Create Exclude,Create Link,Create Icon,Create Text,Create Tooltip,Decimal Format,Decimal Precision,Default,Delimiter,Display Format,Display Time,Dynamic Field Function,Dynamic Field Program,Editable,Edit Count,Edit Exclude,Edit States,Expand Level,Export,Field Column Headers,Field Row Headers,Field Size,Field Table Columns,Field Table Rows,Field Type,Filter BUS,Filter REL,findMxLink,format,From,function,Gallery,Gallery Zoom,Height,Hide Label,Group Name,Help Marker,Hide Label,Hide Mode,Highlight Nonzero Icon,Highlight Nonzero Link,Highlight Nonzero States,Highlight Nonzero Style,Highlight Nonzero Tooltip,Highlight Zero Icon,Highlight Zero Link,Highlight Zero States,Highlight Zero Style,Highlight Zero Tooltip,Icon Link,Icon Tooltip,Image,Image Size,Input Type,inquiry,Label,Latest Label,Latest Link,Latest Threshold,Latest Width,Link More,Max Items,Maximum Length,No Frame,Nowrap,Number Format,OnChange Handler,OnFocus Handler,Pattern Types,Popup Modal   ,Popup Size,Printer Friendly,program,Range Function,Range Program,Read Only Checkbox,Registered Suite,Relationships,Reload Function,Reload Program,Remove Range Blank,Required,Rows,Section Level,Show All View,Show Alternate Icon,Show Clear Button,Show Counter,Show Edit,Show Icons,Show Latest,Show Printer Friendly,Show Table,Show Thumbnails,Show Type Icon,Show View,Slidein Width,Sort Direction,Sort Key,Sort Range Values,Sort Type,sortColumnName,table,Table Actions,Table Cell Rows,Table Columns,Table Link,Table Styles,Target Location,Thumbnail Actions,Thumbnail Details,Thumbnail Link,Thumbnail Size,Thumbnail Styles,Thumbnail Tooltip,Tip Page,Tooltip Separator,Type Ahead Validate,Type Icon Function,Type Icon Program,TypeAhead,TypeAhead Program,TypeAhead Function,TypeAhead Character Count,TypeAhead Saved Values Limit,Types,Update Function,Update Program,Url,Validate,Validate Type,Vertical Group Name,View Exclude,Window Height,Window Width,Zoom,Zoom Window"),
    TABLE_COLUMN("Access Expression,Access Function,Access Mask,Access Program,Add Input Type,Add Link,Additional Query,Admin Type,Allow Manual Edit,Alternate OID expression,Alternate Policy expression,Alternate Type expression,Arithmetic Expression,Auto Filter,autoNumber,Auto Fit Cell,Calculate Average,Calculate Average Label,Calculate Custom,Calculate Custom Label,Calculate Custom Program,Calculate Maximum,Calculate Maximum Label,Calculate Median,Calculate Median Label,Calculate Minimum,Calculate Minimum Label,Calculate Standard Deviation,Calculate Standard DeviationLabel,Calculate Sum,Calculate Sum Label,Calendar Function,Calendar Program,Color Cue Expression,Color Cue Expression Type,Color Cue Label,Color Filter,Colors,Column Icon,Column Type,Comparable,Compare Report,Complete State,Counter Link,Currency Converter,Currency Expression,Decimal Format,Decimal Precision,Default Function,Default Program,Diff Code,Directions,Display Format,Display Time,Display View,Display Mode,DocumentDropRelationship,Drag Types,Draggable,Drop Actions,Drop Directions,Drop Items,Drop JPO,Drop Relationships,Drop Types,Droppable,Dynamic URL,Edit Access Function,Editable,Effective Date Expression,Export,format,function,Group Header,Group Name,Help Marker,Hide Mode,Image Size,Input Control Direction,Input Type,Level,Link More,Lookup Input Type,Mass Update,Max items,Mouse Over Popup,Nowrap,Number Format,On Change Handler,OnFocus Handler,Percentage Format,Popup Modal ,Popup Size,Preserve Spaces setting,Printer Friendly,program,Range Function,Range Program,Registered Suite,Relationships,Reload Function,Reload Program,Required,RMB Menu,Root Label,Row Grouping,Row Grouping Range Function,Row Grouping Range Program,RowGroupCalculation,Row Number,Row Span,Show Alternate Icon,Show Clear Button,Show Counter,Show Drop Zone,Show Icons,Show Link,Show Next,Show Previous,Show Table,Show Type Icon,Sortable,Sort Direction,Sort Key,Sort Range Values,Sort Type,States,Style Column,Style Function,Style Program,Table Columns,Target Location,Type Ahead Mapping,Type Ahead Validate,Type Icon Function,Type Icon Program,UOM Expression,Update Function,Update Program,Validate,Validate Type,Width"),
    PORTAL("Access Behavior,Access Expression,Access Function,Access Program,Hide Mode,Registered Suite,Submit"),
    CHANNEL("Access Behavior,Access Expression,Access Function,Access Program,ChannelID,Default Category,Group Name,Height,Registered Suite,RowID,Width"),
    MENU("Access Behavior,Access Expression,Access Function,Access Map,Access Mask,Access Program,Alignment,Check Derivative,Confirm Message,Currency Converter,Default Category,Default Category Function,Default Category Program,Document Command,DocumentDrop Relationship,Dynamic Command Function,Dynamic Command Program,Expanded,Header Image Upload,Header Lifecycle,HelpMaker,Hide Mode,Horizontal ToolBar,iefcname,iefrefreshpage,iefwaitforresponse,Image,Image Manager Toolbar,Image Upload Command,Image value,ImageDrop Relationship,Label Function,Label Program,Licensed Product,Message URL Label,Mode,Navigator RMB Menu,Popup Modal,Pull Right,Registered Suite,Row Select,Show Navigator RMB,Show Type Icon,Structure Menu,Submit,Target Location,Tree Scope ID,Trigger Validation,Type Icon Function,Type Icon Program,Width,Window Height,Window Width"),
    COMMAND("Access Behavior,Access Expression,Access Function,Access Map,Access Mask,Access Mode,Access Program,Access Program Method,AccessBit,Action Label,Action Type,Admin Type,AdminPartType,Alignment,Allow Manual Edit,Append Parameters,AutoCollaborationParam,Basics,CmdName,Command,Command Name,Command Type,Comparison Operator,Completed Rule,Configuration Context Mode,Confirm Message,Context Selector,Currency Converter,CustomItemObject,Default,DefaultCategory,DefaultDesignCollaborationParam,Display Format,Display View,Drop File CheckIn,Drop Reference Document,Dynamic Command Function,Dynamic Command Program,Dynamic Label Function,Dynamic Label Program,Editable,Enabled,Event Type,Exclude History Attributes,Expand Inquiry,ExpandFilterRelationships,ExpandFilterTypes,expandProgram,Export,Field Size,Field Type,FindNumberBasedRollup,Float History Relationship,Float Relationship,focusbrowser,Force Recursion,Format,FromPortal,function,HasSubCommands,Help Marker,hidden,Hide Label,Hide Mode,History Bit,Icon,IEF Command Name,iefaction,iefcname,iefdoubleclick,iefrefreshpage,iefwaitforresponse,Image,image,Image value,includeContextProgram,Input Type,IntermediateFilterTypes,Is Recursible,IsDefault,isRecentlyCheckedInFiles,itemMarkup,Javascript,JavaScript Include,JS Before Load,keyword,Label,Label Function,Label Program,Left Expression,Level,License Product,Licensed Product,Maximum Length,Mode,Mode Access,Mouse Over Popup,Multilevel Selection Mode,OpenerFrame,Order,Popup Modal,Popup Modal1,Popup Model,Popup Size,PPRObjectType,PreExpand,PreExpand Category,Printer Friendly,program,Pull Right,Range Display Values,Range Function,Range Function1,Range Name,Range Program,Range Program1,Range Values,Recurse Direction,Recurse Relationship,Registered Suite,relationalCriteria,relationship,relationshipType,resetId,Right Expression,Row Select,searchType,Select,Selectable in Preferences,Selection,sequenceSelectable,seriesType,Show Clear Button,Show Type Icon,showAnd,showInfinity,ShowParentHierarchy,Single Click,Slidein Width,Sortable,State,Structure Function,Structure Program,Submit,Submit Action,Submit1,table,Target,Target Location,Target Location1,toolbar,Tooltip,Tree Scope ID,type,ValidationForBasics,ValidationForCompletedRule,ValidationForContextSelector,ValidationForLeftExpression,ValidationForRightExpression,Width,Window Height,Window Width");

    private String name;

    SpinnerSettingNameConfig(String name) {
        this.name = name;
    }

    public static List<String> getSettingNames(SpinnerType spinnerType) {
        return switch (spinnerType) {
            case MENU -> splitName(MENU);
            case COMMAND -> splitName(COMMAND);
            case PORTAL -> splitName(PORTAL);
            case CHANNEL -> splitName(CHANNEL);
            case FORM_FIELD -> splitName(FORM_FIELD);
            case TABLE_COLUMN -> splitName(TABLE_COLUMN);
            default -> throw new IllegalStateException();
        };
    }

    static List<String> splitName(SpinnerSettingNameConfig config) {
        return CharSequenceUtil.split(config.name, ",");
    }
}
